#!/usr/bin/env python3.12
"""Run a bound prompt, measure the sources around it, and write the evidence record.

`run_bound.py` calls the model with nothing around it. This is the same call
with the integrity check attached: measure the real source files before and
after the run, run, write the record. It is the composition that produced
`runs/pivot_smoke.qwen3.5-9b.20260805T091739.md` on 5 Aug 2026 and was then
lost — no file in this repo's history has ever called `evidence_log.write`,
so that record could not be reproduced. This file is that recipe, kept.

    python3.12 run_sealed.py verify gemma4:12b

NO CELL ON THIS PATH — dropped 11 Aug 2026 (TODO !55), Scott's ruling. The
occupant is an HTTP call to Ollama; nothing ever ran inside the cell and
nothing could write to it, so the cell's own internal manifest could only
ever read INTACT — it measured a static copy nobody touched. The real check
was always `external_paths`: the actual source files the prompt was composed
from, which something on this machine genuinely could edit mid-run. That
check is what remains. `attest.freeze` still needs a directory to walk, so a
throwaway scratch dir stands in for it — nothing is copied into it, nothing
is declared evidence, nothing is sealed. Dropping the cell removed a control
that duplicated `external_paths` without closing any failure it didn't
already close (Law 1 SIMPLE/ROBUST).

WHAT THIS PROVES HERE, stated narrowly. The measurement establishes that the
source bytes the prompt was built from did not change across the run. It does
not establish containment: containment is the UID boundary, SPEC §8 step 0,
still UNKNOWN.

The verdict is UNKNOWN and is not computed here. `gauge` adjudicates against a
bundle and a contract that this path does not have, and writing anything else
into that field would be a second adjudicator in the tree, which SPEC §2 rule 5
forbids. UNKNOWN is the honest value, and it is the one the 5 Aug record
carries for the same reason.
"""
import datetime
import hashlib
import os
import pathlib
import sys
import tempfile

import attest
import build_paste
import evidence_log
import occupant_bound

# attest names three integrity states; the evidence log's schema names two.
# The mapping is written out rather than inferred, and UNKNOWN deliberately has
# no entry: a run whose integrity could not be determined has no delta to
# report, and evidence_log refuses a missing field rather than inventing one.
DELTA_FOR = {attest.INTACT: "CLEAN", attest.BYPASSED: "MODIFIED"}


def digest(path):
    return "sha256:" + hashlib.sha256(pathlib.Path(path).read_bytes()).hexdigest()[:12]


STERILE_FAILURES = pathlib.Path(build_paste.BS) / "runs" / "STERILE_FAILURES.md"


def log_sterile_failure(job, model, stamp, report, note):
    """One entry per run whose watched source files did not come back clean.

    Its own file, and separate from the ramp's for a reason: the ramp records a
    model getting an answer wrong, this records the measurement reporting that
    bytes moved. They are different kinds of bad, and a reader scanning for one
    should not have to sift the other. Neither belongs in FAILURE_LOG.md, whose
    entry rule admits withdrawn designs in a fixed form.
    """
    STERILE_FAILURES.parent.mkdir(parents=True, exist_ok=True)
    new = not STERILE_FAILURES.exists()
    deltas = (report or {}).get("deltas") or []
    with STERILE_FAILURES.open("a") as f:
        if new:
            f.write("# SEALED RUNS — FAILED STERILITY\n\nOne entry per run whose "
                    "watched source files did not come back as they went in. Each "
                    "names the paths that moved. Measurements, not design "
                    "rulings: see FAILURE_LOG.md for those.\n")
        f.write(
            f"\n---\n\n## {job} · {model} · {stamp}\n"
            f"- integrity: {(report or {}).get('integrity', 'no comparison reached')}\n"
            f"- detail: {(report or {}).get('detail', note)}\n"
            f"- paths that changed: {len(deltas)}\n")
        for d in deltas[:40]:
            f.write(f"    - {d['change']}: {d['path']}\n")
        if len(deltas) > 40:
            f.write(f"    - … and {len(deltas) - 40} more\n")


def originals_for(spec_job):
    """Every real file the prompt was composed from — kernel, job, sources.

    These are the only paths that matter now there is no cell: the composed
    paste file is not among them, since it is regenerated by
    `build_paste.build` on every run and would report a delta on every run,
    meaning nothing.
    """
    return [build_paste.KERNEL, spec_job["job"]] + [p for _, p in spec_job["sources"]]


def main(job, model, variant="flat"):
    if job not in build_paste.JOBS:
        raise SystemExit(f"unknown job {job!r}: {sorted(build_paste.JOBS)}")
    if model not in occupant_bound.CLEAN_MODELS:
        raise SystemExit(
            f"refusing {model!r}: not a clean base model. "
            f"Use one of {sorted(occupant_bound.CLEAN_MODELS)}")
    if variant not in build_paste.VARIANTS:
        raise SystemExit(f"unknown variant {variant!r}: {sorted(build_paste.VARIANTS)}")

    spec_job = build_paste.JOBS[job]
    if variant == "flat":
        # Byte-identical to the production path: build() writes spec["out"],
        # this reads it back unchanged. Every job this repo has ever run
        # through run_sealed.py used this branch; it stays untouched.
        build_paste.build(job)
        prompt, system = spec_job["out"].read_text(), None
    else:
        prompt, system = build_paste.compose_variant(job, variant)
    stamp = datetime.datetime.now().strftime("%Y%m%dT%H%M%S")

    report = None
    # `attest.freeze` needs a directory to walk; nothing is ever put in this
    # one and nothing is declared evidence — the real check is `external_paths`
    # below. Self-cleaning, so there is nothing left to tear down or preserve.
    with tempfile.TemporaryDirectory(prefix="blacksmith-scratch-") as scratch:
        try:
            originals = tuple(str(p) for p in originals_for(spec_job))
            pre = attest.freeze("pre", scratch, external_paths=originals)
            print(f"pre-attest frozen ({len(originals)} source files watched)", flush=True)

            # The reply is written beside the record under the same naming
            # convention run_bound.py uses, so both land in the same set.
            # Variant tag included (flat omits it) so 3 variants of one job
            # against one model don't collide or silently overwrite. Paths
            # are computed before the call (not after) so occupant_bound.run
            # can stream into them as tokens arrive — a run that never
            # finishes still leaves what it got, same as run_bound.py
            # (TODO !92).
            tag = model.replace(":", "-") if variant == "flat" else f"{model.replace(':', '-')}.{variant}"
            reply = evidence_log.OUT_DIR / f"{job}.{tag}.{stamp}.reply.md"
            reply.parent.mkdir(parents=True, exist_ok=True)
            think_path = reply.parent / (reply.stem.removesuffix(".reply") + ".thinking.md")

            print(f"{model} [{variant}]: sending {len(prompt):,} chars prompt"
                  f"{f' + {len(system):,} chars system' if system else ''}"
                  f" — silent while it reasons", flush=True)
            run = occupant_bound.run(
                model, prompt, system=system, reply_path=reply, think_path=think_path)
            print(f"first token {run.first_token_s:,.1f}s, "
                  f"final {run.final_token_s:,.1f}s, {len(run.response):,} reply chars, "
                  f"{len(run.thinking):,} reasoning chars",
                  flush=True)

            # Reasoning goes to its own file, never into the reply — same rule
            # run_bound.py follows and for the same reason: the reply is what
            # quotes.py scans, and mixing the two would hand a checker the
            # model's self-persuasion as if it were the answer. occupant_bound
            # only opens think_path if there was a first thought to write, so
            # empty thinking still means no file — same as before.
            if not run.thinking:
                think_path = None

            post = attest.freeze("post", scratch, external_paths=originals)
            report = attest.compare(pre, post)
            print(f"integrity: {report['integrity']} — {report['detail']}", flush=True)

            if report["integrity"] not in DELTA_FOR:
                raise SystemExit(
                    f"integrity is {report['integrity']}: {report['detail']}. No "
                    "evidence entry written — a record with an invented delta is "
                    "worse than no record.")

            written = evidence_log.write(
                job=job, model=model, timestamp=stamp,
                launch=evidence_log.LaunchRecord(
                    launched_by=f"uid:{os.getuid()}",
                    started_at=datetime.datetime.now(datetime.UTC).isoformat(),
                    kernel_digest=digest(build_paste.KERNEL),
                    job_digest=digest(spec_job["job"]),
                    evidence_mode="none"),
                execution=evidence_log.Execution(
                    first_token=f"{run.first_token_s:.2f}s",
                    final_token=f"{run.final_token_s:.2f}s",
                    exit_code=run.exit_code if run.done_reason == "stop" else run.done_reason),
                integrity=evidence_log.IntegrityReport(
                    makers_mark_pre=pre.root_hash(),
                    makers_mark_post=post.root_hash(),
                    delta=DELTA_FOR[report["integrity"]],
                    verdict="UNKNOWN"),
                lesson=(
                    f"Bound occupant over HTTP, no cell (dropped 11 Aug, TODO !55) — "
                    f"only the {len(originals)} real source files were watched. "
                    f"Integrity {report['integrity']}: {report['detail']}. Verdict "
                    f"UNKNOWN — gauge has no bundle or contract on this path and "
                    f"does not guess. Reply at {reply.name}, adjudicate with "
                    f"quotes.py before reading it."
                    + (f" Reasoning ({len(run.thinking):,} chars) at {think_path.name}."
                       if think_path is not None else "")
                    + f" Binding variant: {variant}"
                    + (f", Laws in system field ({len(system):,} chars)."
                       if system else ", Laws in flat prompt (no system field).")))
            print(f"wrote {written.relative_to(build_paste.BS)}")
            print(f"reply {reply.relative_to(build_paste.BS)}")
            if think_path is not None:
                print(f"reasoning {think_path.relative_to(build_paste.BS)}")
        finally:
            # Guaranteed regardless of how the try block exits: an exception
            # before `attest.compare` leaves `report` at None, and an UNKNOWN
            # integrity raises SystemExit above before any explicit log call
            # would run. Both are states worth a record, same as BYPASSED —
            # the old cell-based version logged all three via this same
            # unconditional finally; a single inline call after the SystemExit
            # check would have silently dropped both, found on reread, not by
            # running.
            if report is None or report["integrity"] != attest.INTACT:
                log_sterile_failure(
                    job, f"{model} [{variant}]", stamp, report,
                    note="run ended before the comparison was reached")
                print(f"logged to {STERILE_FAILURES.name}", flush=True)


if __name__ == "__main__":
    if len(sys.argv) not in (3, 4):
        raise SystemExit(
            f"usage: run_sealed.py <job> <model> [variant]  "
            f"variants: {sorted(build_paste.VARIANTS)}")
    main(sys.argv[1], sys.argv[2], sys.argv[3] if len(sys.argv) == 4 else "flat")
