#!/usr/bin/env python3.12
"""Run a bound prompt inside a sealed, measured cell and write the evidence record.

`run_bound.py` calls the model with nothing around it. This is the same call
with Ring 0 attached: build a sterile cell holding the sources, measure it,
run, measure again, write the record. It is the composition that produced
`runs/pivot_smoke.qwen3.5-9b.20260805T091739.md` on 5 Aug 2026 and was then
lost — no file in this repo's history has ever called `evidence_log.write`,
so that record could not be reproduced. This file is that recipe, kept.

    python3.12 run_sealed.py verify gemma4:12b

WHERE THE CELL LIVES, and why it is not in this repo. `cell.build` refuses a
location with host-context files above it, and `~/.claude` sits above the
whole of `~/Documents` — so every path in this tree is contaminated and a cell
cannot be built in any of them. CELLS_ROOT is therefore outside the home
directory entirely. That refusal is the point, not an obstacle routed around.

WHAT THE CELL PROVES HERE, stated narrowly. The occupant is an HTTP call, so
nothing runs inside the cell and nothing could write to it. The measurement
establishes that the source bytes the prompt was built from did not change
across the run. It does not establish containment: containment is the UID
boundary, SPEC §8 step 0, still UNKNOWN.

The verdict is UNKNOWN and is not computed here. `gauge` adjudicates against a
bundle and a contract that this path does not have, and writing anything else
into that field would be a second adjudicator in the tree, which SPEC §2 rule 5
forbids. UNKNOWN is the honest value, and it is the one the 5 Aug record
carries for the same reason.
"""
import datetime
import hashlib
import os
import pathlib
import sys

import attest
import build_paste
import cell as cell_mod
import evidence_log
import occupant_bound

# Outside the home directory, because everything inside it is contaminated.
CELLS_ROOT = pathlib.Path("/private/tmp/blacksmith-cells")

# attest names three integrity states; the evidence log's schema names two.
# The mapping is written out rather than inferred, and UNKNOWN deliberately has
# no entry: a run whose integrity could not be determined has no delta to
# report, and evidence_log refuses a missing field rather than inventing one.
DELTA_FOR = {attest.INTACT: "CLEAN", attest.BYPASSED: "MODIFIED"}


def digest(path):
    return "sha256:" + hashlib.sha256(pathlib.Path(path).read_bytes()).hexdigest()[:12]


STERILE_FAILURES = pathlib.Path(build_paste.BS) / "runs" / "STERILE_FAILURES.md"


def log_sterile_failure(job, model, stamp, root, report, note):
    """One entry per run that did not come back sterile.

    Its own file, and separate from the ramp's for a reason: the ramp records a
    model getting an answer wrong, this records the *seal* reporting that bytes
    moved. They are different kinds of bad, and a reader scanning for one should
    not have to sift the other. Neither belongs in FAILURE_LOG.md, whose entry
    rule admits withdrawn designs in a fixed form.

    Written BEFORE the cell is preserved and never inside it — an account of a
    contaminated tree that lives in the contaminated tree is not evidence.
    """
    STERILE_FAILURES.parent.mkdir(parents=True, exist_ok=True)
    new = not STERILE_FAILURES.exists()
    deltas = (report or {}).get("deltas") or []
    with STERILE_FAILURES.open("a") as f:
        if new:
            f.write("# SEALED RUNS — FAILED STERILITY\n\nOne entry per run whose "
                    "cell or sources did not come back as they went in. Each "
                    "names the paths that moved. Measurements, not design "
                    "rulings: see FAILURE_LOG.md for those.\n")
        f.write(
            f"\n---\n\n## {job} · {model} · {stamp}\n"
            f"- integrity: {(report or {}).get('integrity', 'no comparison reached')}\n"
            f"- detail: {(report or {}).get('detail', note)}\n"
            f"- cell kept at: {root}\n"
            f"- paths that changed: {len(deltas)}\n")
        for d in deltas[:40]:
            f.write(f"    - {d['change']}: {d['path']}\n")
        if len(deltas) > 40:
            f.write(f"    - … and {len(deltas) - 40} more\n")


def originals_for(spec_job):
    """Every real file the prompt was composed from — kernel, job, sources.

    These are the paths outside the cell. The composed paste file is not among
    them: it is regenerated by `build_paste.build` on every run, so it would
    report a delta on every run and mean nothing.
    """
    return [build_paste.KERNEL, spec_job["job"]] + [p for _, p in spec_job["sources"]]


def main(job, model):
    if job not in build_paste.JOBS:
        raise SystemExit(f"unknown job {job!r}: {sorted(build_paste.JOBS)}")
    if model not in occupant_bound.CLEAN_MODELS:
        raise SystemExit(
            f"refusing {model!r}: not a clean base model. "
            f"Use one of {sorted(occupant_bound.CLEAN_MODELS)}")

    spec_job = build_paste.JOBS[job]
    build_paste.build(job)
    prompt = spec_job["out"].read_text()
    stamp = datetime.datetime.now().strftime("%Y%m%dT%H%M%S")

    CELLS_ROOT.mkdir(parents=True, exist_ok=True)
    # Every source the prompt was composed from goes in as evidence, so the
    # measurement covers the bytes the run actually depended on.
    built = cell_mod.build(cell_mod.CellSpec(
        root=CELLS_ROOT / f"{job}.{model.replace(':', '-')}.{stamp}",
        evidence_mode="copy",
        evidence_sources=tuple(p for _, p in spec_job["sources"]),
        # Strict: nothing runs in the cell, so nothing may write to it. Any
        # change at all is a change that should not have happened.
        scratch_prefixes=(),
    ))
    print(f"cell built at {built.root}", flush=True)

    report = None
    try:
        # The cell holds COPIES of the sources; the prompt was composed from the
        # originals. Measuring only the cell would report CLEAN while the bytes
        # the model actually read were edited underneath it — the seal watching
        # the wrong files. `external_paths` exists for exactly this: the
        # originals are measured alongside the cell, so a change to either side
        # is a delta.
        args = cell_mod.attest_args(built)
        originals = tuple(str(p) for p in originals_for(spec_job))
        pre = attest.freeze("pre", external_paths=originals, **args)
        print(f"pre-attest frozen ({len(pre.entries)} paths in cell, "
              f"{len(originals)} originals outside it)", flush=True)

        print(f"{model}: sending {len(prompt):,} chars — silent while it reasons",
              flush=True)
        run = occupant_bound.run(model, prompt)
        print(f"first token {run.first_token_s:,.1f}s, "
              f"final {run.final_token_s:,.1f}s, {len(run.response):,} chars",
              flush=True)

        post = attest.freeze("post", external_paths=originals, **args)
        report = attest.compare(pre, post)
        print(f"integrity: {report['integrity']} — {report['detail']}", flush=True)

        if report["integrity"] not in DELTA_FOR:
            raise SystemExit(
                f"integrity is {report['integrity']}: {report['detail']}. No "
                "evidence entry written — a record with an invented delta is "
                "worse than no record.")

        # The reply is written beside the record under the same naming
        # convention run_bound.py uses, so both land in the same set.
        reply = evidence_log.OUT_DIR / f"{job}.{model.replace(':', '-')}.{stamp}.reply.md"
        reply.parent.mkdir(parents=True, exist_ok=True)
        reply.write_text(run.response, encoding="utf-8")

        written = evidence_log.write(
            job=job, model=model, timestamp=stamp,
            launch=evidence_log.LaunchRecord(
                launched_by=f"uid:{os.getuid()}",
                started_at=datetime.datetime.now(datetime.UTC).isoformat(),
                kernel_digest=digest(build_paste.KERNEL),
                job_digest=digest(spec_job["job"]),
                evidence_mode=built.spec.evidence_mode),
            execution=evidence_log.Execution(
                first_token=f"{run.first_token_s:.2f}s",
                final_token=f"{run.final_token_s:.2f}s",
                exit_code=run.exit_code if run.done_reason == "stop" else run.done_reason),
            integrity=evidence_log.IntegrityReport(
                cell_pre_hash=pre.root_hash(),
                cell_post_hash=post.root_hash(),
                delta=DELTA_FOR[report["integrity"]],
                verdict="UNKNOWN"),
            lesson=(
                f"Bound occupant over HTTP, sealed cell at {built.root}, "
                f"scratch declared empty. Integrity {report['integrity']}: "
                f"{report['detail']}. Verdict UNKNOWN — gauge has no bundle or "
                f"contract on this path and does not guess. Reply at "
                f"{reply.name}, adjudicate with quotes.py before reading it."))
        print(f"wrote {written.relative_to(build_paste.BS)}")
        print(f"reply {reply.relative_to(build_paste.BS)}")
    finally:
        # Kept, not destroyed, unless the cell came back exactly as it went in.
        # Tearing down on every path would delete the changed bytes at the one
        # moment they are worth having: a MODIFIED verdict names *that* something
        # changed, and only the cell itself shows *what*. `report` is unset if the
        # failure came before the comparison, which is also a state to preserve.
        if report is not None and report["integrity"] == attest.INTACT:
            cell_mod.teardown(built.root, CELLS_ROOT)
            print("cell torn down — nothing changed in it", flush=True)
        else:
            log_sterile_failure(job, model, stamp, built.root, report,
                                note="run ended before the comparison was reached")
            print(f"logged to {STERILE_FAILURES.name}", flush=True)
            print(f"cell KEPT for inspection at {built.root}\n"
                  f"  it is sealed read-only; remove it with:\n"
                  f"    chmod -R u+w {built.root} && rm -rf {built.root}",
                  flush=True)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit("usage: run_sealed.py <job> <model>")
    main(sys.argv[1], sys.argv[2])
